In [11]:
import numpy as np
import pandas as pd

**Nomor 1**

In [31]:
# input
start = int(input('Mulai: '))
end  = int(input('Selesai: '))

Mulai: 1
Selesai: 28


In [32]:
# 1 dimensi
np.arange(start,end)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [33]:
# 2 dimensi
np.arange(start,end).reshape((3,-1))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [34]:
# 3 dimensi
np.arange(start,end).reshape((3,3,-1))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

**Nomor 2**

In [35]:
length = int(input('Banyak Data: '))
start = int(input('Mulai: '))
end = int(input('Selesai: '))

Banyak Data: 16
Mulai: 1
Selesai: 50


In [42]:
# 1 dimensi
answer2 = np.random.randint(start,end,size=length)
answer2

array([33, 43, 11,  5,  6, 18, 29,  9, 47, 15,  6, 49, 37, 16,  1, 10])

In [45]:
# 2 dimensi
answer2 = answer2.reshape(4,-1)
answer2

array([[33, 43, 11,  5],
       [ 6, 18, 29,  9],
       [47, 15,  6, 49],
       [37, 16,  1, 10]])

In [71]:
# tukar posisi
np.flip(answer2,axis=1)

array([[ 5, 11, 43, 33],
       [ 9, 29, 18,  6],
       [49,  6, 15, 47],
       [10,  1, 16, 37]])

**Nomor 3**

In [113]:
answer3 =np.linspace(4,4,100).reshape(10,10)
answer3[1:-1,1:-1] = 0
answer3

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

**Nomor 4**

In [125]:
import string
pd.Series(data=list(range(1, 27)), index=list(string.ascii_lowercase))


a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int64

**Nomor 5**

In [128]:
# series yang terdiri dari angka random integer 1 sampai 5 sebanyak 100
answer5 = pd.Series(np.random.randint(1,5,100))
answer5

0     4
1     3
2     2
3     1
4     3
     ..
95    2
96    4
97    3
98    1
99    1
Length: 100, dtype: int64

In [130]:
# menghitung banyaknya jumlah setiap angka
pd.value_counts(answer5)

1    32
4    26
2    23
3    19
dtype: int64

In [140]:
# mencari tahu 2 angka terbanyak
pd.value_counts(answer5).to_frame(name="Frequency").reset_index().rename(columns = {'index':'value'}).head(2)


value  Frequency
0      1         32
1      4         26

**Nomor 6**

In [261]:
# import seaborn dan load data 'MPG'
import seaborn as sns
mpg = sns.load_dataset('mpg')

In [143]:
# tampilkan 5 data teratas 
mpg.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [144]:
# tampilkan statistik deskriptif selain data numeric
mpg.describe(include=object)

origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6

In [147]:
# tampilkan seluruh nama kolom
mpg.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [149]:
# hitung jumlah missing value di setiap kolom
mpg.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

**Nomor 7**

In [152]:
# menampilkan data missing value pada kolom horsepower
mpg[mpg['horsepower'].isna()]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
32   25.0          4          98.0         NaN    2046          19.0   
126  21.0          6         200.0         NaN    2875          17.0   
330  40.9          4          85.0         NaN    1835          17.3   
336  23.6          4         140.0         NaN    2905          14.3   
354  34.5          4         100.0         NaN    2320          15.8   
374  23.0          4         151.0         NaN    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl

In [153]:
# tampilkan index lokasi missing value tersebut
mpg[mpg['horsepower'].isna()].index

Int64Index([32, 126, 330, 336, 354, 374], dtype='int64')

**Nomor 8**

In [154]:
#horsepower berdasarkan year
mpg.groupby('model_year').mean()['horsepower']

model_year
70    147.827586
71    107.037037
72    120.178571
73    130.475000
74     94.230769
75    101.066667
76    101.117647
77    105.071429
78     99.694444
79    101.206897
80     77.481481
81     81.035714
82     81.466667
Name: horsepower, dtype: float64

**Nomor 9**

In [300]:
# membuat fungsinya
def conditions(x):
    if x['horsepower'] is np.nan:
        return np.nan
    elif x['horsepower'] <= 105:
        return 'lower ' + x['origin']
    else:
        return 'upper ' + x['origin']

In [301]:
# membuat kolom baru dari fungsi
mpg['horse_origin'] = mpg.apply(conditions, axis=1)
mpg

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  horse_origin  
0            70     usa  chevrolet chevelle malibu     upper usa  
1            70     usa          buick skylark 320     upper usa  
2            70     usa         plymouth satellite     upper usa  
3            70     usa              amc rebel sst     upper usa  
4            70     usa                ford torino     upper usa  
..          ...     ...                        ...           ...  
393          82     usa            ford mustang gl     lower usa  
394          82  europe                  vw pickup  lower europe  
395          82     usa              dodge rampage     lower usa  
396          82     usa                ford ranger     lower usa  
397          82     usa                 chevy s-10     lower usa  

[398 rows x 10 columns]

**Nomor 10**

In [348]:
# buat grouping untuk aggregate yang ditentukan
answer10 = mpg.groupby('origin').agg(['mean', 'std', 'sum', 'count', 'min', 'max'])['weight']
answer10

mean         std     sum  count   min   max
origin                                                    
europe  2423.300000  490.043191  169631     70  1825  3820
japan   2221.227848  320.497248  175477     79  1613  2930
usa     3361.931727  794.792506  837121    249  1800  5140

In [350]:
# reset index
answer10.reset_index()

origin         mean         std     sum  count   min   max
0  europe  2423.300000  490.043191  169631     70  1825  3820
1   japan  2221.227848  320.497248  175477     79  1613  2930
2     usa  3361.931727  794.792506  837121    249  1800  5140